#!/bin/bash

icons_dir=$HOME/.local/share/icons

mkdir $icons_dir
cp -r cursors/* $icons_dir
cp -r icons/* $icons_dir

gtk-update-icon-cache
#gsettings set org.gnome.desktop.interface cursor-theme 'Quogir-Cursor'
